#!/bin/sh

DEF_REPO="mesg-foundation/core"
DEF_BRANCH="master"
DIR="./"

rm -rf src/protobuf
mkdir -p src/protobuf
cd src/protobuf

filepaths="coreapi/api serviceapi/api definition/service"
for filepath in $filepaths; do
    mkdir -p $(dirname "${filepath}")
    curl -o "${filepath}.proto" "https://raw.githubusercontent.com/$DEF_REPO/$DEF_BRANCH/protobuf/${filepath}.proto"
done
