#!/bin/sh

DEF_REPO="mesg-foundation/core"
DEF_BRANCH="dev"
PROTO_PATH="https://raw.githubusercontent.com/$DEF_REPO/$DEF_BRANCH/protobuf"
DIR="./"

rm -rf src/protobuf
mkdir -p src/protobuf/api
mkdir -p src/protobuf/types

ressources="event execution instance service"
for ressource in $ressources; do
  curl -o "./src/protobuf/api/${ressource}.proto" "$PROTO_PATH/api/${ressource}.proto"
  curl -o "./src/protobuf/types/${ressource}.proto" "$PROTO_PATH/types/${ressource}.proto"
done
curl -o "./src/protobuf/api/core.proto" "$PROTO_PATH/coreapi/api.proto"
