#!/bin/sh

# Path to this plugin, Note this must be an abolsute path on Windows (see #15)
PROTOC_GEN_TS_PATH="$(pwd)/node_modules/.bin/protoc-gen-ts"

# Directory to write generated code to (.js and .d.ts files) 
DIR="./"

cd src/client

protoc \
    --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
    --js_out="import_style=commonjs,binary:${DIR}" \
    --ts_out="service=true:${DIR}" \
    api-core.proto

protoc \
    --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
    --js_out="import_style=commonjs,binary:${DIR}" \
    --ts_out="service=true:${DIR}" \
    api-service.proto