version: 2

runOnDocker: &runOnDocker
  working_directory: ~/mesg-js
  docker:
    - image: circleci/node:10.15.0

jobs:
  test:
    <<: *runOnDocker
    steps:
      - checkout
      - run: ls
      - run: npm install
      - run: npm test
      - run: npm run coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2

  test_commit:
    jobs:
      - test